name: Dependency CI

on:
  pull_request:
  workflow_dispatch:


jobs:
  release-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install Depp 
        run: go install github.com/cryogenicplanet/depp@latest
      - name: Run Depp
        run: depp --ci
        env:
            NETLIFY_TOKEN: ${{secrets.NETLIFY_TOKEN}}
            # Optional if you want report urls or not
            # You can get a netlify pat here https://app.netlify.com/user/applications#personal-access-tokens